### ISSUE TITLE
failed to solve: process "/bin/sh -c apt-get update     && apt-get install -y --no-install-recommends curl nodejs libgmp-dev

### ISSUE THREAD

**Issue by tcexeexe** [YFGaia/dify-plus#6]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.15.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1、modeify the all image to build in docker-compose.dify-plus.yaml

```
    # image: famousmai/dify-plus-api:0.0.4
    build:
      context: ../api
      dockerfile: ./Dockerfile
    restart: always
```

```
    # image: famousmai/dify-plus-admin-web:0.0.2
    build:
      context: ../admin/web
      dockerfile: ./Dockerfile
```

```
    # image: famousmai/dify-plus-web:0.0.4
    build:
      context: ../web
      dockerfile: ./Dockerfile
```

```
    # image: famousmai/dify-plus-admin-web:0.0.2
    build:
      context: ../admin/web
      dockerfile: ./Dockerfile
```

then run 
`sudo docker compose -f docker-compose.dify-plus.yaml up -d`

### ❌ Actual Behavior

<img width="716" alt="Image" src="https://github.com/user-attachments/assets/3544e2b2-24f3-4769-8c9c-b303581e999e" />
